# Generated by Django 3.1.4 on 2020-12-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformity',
            name='type',
            field=models.CharField(choices=[('NEAR_MISS', 'Near Miss'), ('WORK_ACCIDENT', 'Work Accident'), ('UNSAFE_ACT', 'Unsafe Act'), ('UNSAFE_CONDITION', 'Unsafe Condition')], default='NEAR_MISS', max_length=20),
        ),
    ]
