# Generated by Django 3.1.4 on 2021-01-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0002_nonconformity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonconformity',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='nonconformity',
            old_name='Occurrence Date',
            new_name='occ_date',
        ),
    ]
